export const NAVIGATION = [
  { label: "Home", href: "/", icon: "⌂", iconName: "home" },
  { section: "PLAN" },
  { label: "Date", href: "/date", icon: "○", iconName: "date" },
  { label: "Trip", href: "/trip", icon: "◇", iconName: "trip" },
  { label: "Calendar", href: "/calendar", icon: "□", iconName: "calendar" },
  { section: "DISCOVER" },
  { label: "Places", href: "/places", icon: "⌖", iconName: "places" },
  { label: "Our Map", href: "/our-map", icon: "⌁", iconName: "map" },
  { section: "REMEMBER" },
  { label: "Memories", href: "/memories", icon: "▧", iconName: "memories" },
  { section: "KEEP" },
  { label: "Vault", href: "/vault", icon: "▣", iconName: "vault" },
  { label: "Gifts", href: "/gifts", icon: "▤", iconName: "gifts" },
  { label: "Bucket", href: "/bucket", icon: "▢", iconName: "bucket" },
  { section: "TOGETHER" },
  { label: "Partner", href: "/invite", icon: "◎", iconName: "partner" },
  { label: "Insights", href: "/insights", icon: "∿", iconName: "insights" },
] as const;

export const SEARCH_COMMANDS = [
  { href: "/trip", label: "여행 일정 열기", icon: "◇" },
  { href: "/date", label: "데이트 일정 열기", icon: "○" },
  { href: "/calendar", label: "캘린더 보기", icon: "□" },
  { href: "/places", label: "장소 찾기", icon: "⌖" },
  { href: "/memories", label: "추억 남기기", icon: "▧" },
  { href: "/vault", label: "보관함 열기", icon: "▣" },
  { href: "/gifts", label: "선물 메모", icon: "▤" },
  { href: "/bucket", label: "버킷리스트", icon: "▢" },
  { href: "/our-map", label: "우리 지도 열기", icon: "⌁" },
  { href: "/insights", label: "우리 데이트 기준", icon: "∿" },
  { href: "/invite", label: "파트너 관리", icon: "◎" },
] as const;
