export const NAVIGATION = [
  { label: "Home", href: "/", icon: "⌂" },
  { section: "PLAN" },
  { label: "Date", href: "/date", icon: "○" },
  { label: "Trip", href: "/trip", icon: "◇" },
  { label: "Calendar", href: "/calendar", icon: "□" },
  { section: "DISCOVER" },
  { label: "Places", href: "/places", icon: "⌖" },
  { label: "Our Map", href: "/our-map", icon: "⌁" },
  { section: "REMEMBER" },
  { label: "Memories", href: "/memories", icon: "▧" },
  { section: "KEEP" },
  { label: "Vault", href: "/vault", icon: "▣" },
  { label: "Gifts", href: "/gifts", icon: "▤" },
  { label: "Bucket", href: "/bucket", icon: "▢" },
  { section: "TOGETHER" },
  { label: "Insights", href: "/insights", icon: "∿" },
] as const;

export const SEARCH_COMMANDS = [
  { href: "/trip", label: "여행 일정 열기", icon: "◇" },
  { href: "/date", label: "데이트 일정 열기", icon: "○" },
  { href: "/calendar", label: "캘린더 보기", icon: "□" },
  { href: "/places", label: "장소 찾기", icon: "⌖" },
  { href: "/memories", label: "추억 남기기", icon: "▧" },
  { href: "/vault", label: "보관함 열기", icon: "▣" },
  { href: "/gifts", label: "선물 메모", icon: "▤" },
  { href: "/bucket", label: "버킷리스트", icon: "▢" },
  { href: "/our-map", label: "우리 지도 열기", icon: "⌁" },
  { href: "/insights", label: "취향 다시 보기", icon: "∿" },
  { href: "/invite", label: "파트너 초대", icon: "◎" },
] as const;
